version: '3.4'
services:

  anystore-api:
    container_name: anystore-api
    image: warleyvods/anystore-api
    networks:
      - sicoob-net
    environment:
      - DATABASE_CONNECTION_URL=jdbc:postgresql://db3:5432/anystore
      - USER=anystore
      - PASSWORD=99433900
      - SCOPE=prod
      - SECRET=eyJhbGciOiJIUzI1NiJ9eyJPb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiACJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI
      - NEW_RELIC_LICENSE_KEY=1f200948d2b1c9461b422893c9f32a942016NRAL
      - NEW_RELIC_APP_NAME=anystore
      - NEW_RELIC_LOG=stdout
      - NEW_RELIC_LOG_LEVEL=info
    depends_on:
      - db3
    links:
      - db3
    restart: on-failure
    labels:
      - traefik.port=9000
      - traefik.http.routers.anystore-api.rule=Host(`anystore-api.wavods.com`)
      - traefik.enable=true
      - traefik.http.routers.anystore-api.entrypoints=websecure
      - traefik.http.routers.anystore-api.tls=true
      - traefik.http.routers.anystore-api.tls.certresolver=myresolver

  db3:
    image: postgres:10-alpine
    container_name: db3
    hostname: db3
    restart: always
    networks:
      - sicoob-net
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=anystore
      - POSTGRES_PASSWORD=99433900
      - POSTGRES_DB=anystore
    volumes:
      - './anystore_postgres/pg_db:/var/lib/postgresql'
      - './anystore_postgres/pg_data:/var/lib/postgresql/data'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

networks:
  sicoob-net:
    driver: bridge
