
spring:
  application:
    name: fbills

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    default-property-inclusion: non_null
    deserialization:
      fail-on-null-for-primitives: true

  profiles:
    active: ${SCOPE:stage}

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

api:
  app:
    jwtCookieName: token
    jwtSecret: ${SECRET:localSecret}
    jwtExpirationMs: 86400000


cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    bucket:
      name: anystorebucket
